[2025-06-24T01:57:16.017+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-24T01:57:16.096+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract scheduled__2025-06-23T00:00:00+00:00 [queued]>
[2025-06-24T01:57:16.102+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract scheduled__2025-06-23T00:00:00+00:00 [queued]>
[2025-06-24T01:57:16.102+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-24T01:57:16.111+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2025-06-23 00:00:00+00:00
[2025-06-24T01:57:16.116+0000] {standard_task_runner.py:63} INFO - Started process 2324 to run task
[2025-06-24T01:57:16.119+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'extract', 'scheduled__2025-06-23T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpr9kggz2e']
[2025-06-24T01:57:16.121+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask extract
[2025-06-24T01:57:16.171+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.extract scheduled__2025-06-23T00:00:00+00:00 [running]> on host ecff408c7856
[2025-06-24T01:57:16.251+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-06-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-23T00:00:00+00:00'
[2025-06-24T01:57:16.252+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-24T01:57:16.254+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-24T01:57:16.254+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_dag.py", line 25, in extract
    return _extract().to_dict(orient="records")
           ^^^^^^^^^^
  File "/opt/airflow/app/pipeline.py", line 19, in extract
    return pd.read_csv(CSV_PATH)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/app/data/input.csv'
[2025-06-24T01:57:16.267+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=extract, run_id=scheduled__2025-06-23T00:00:00+00:00, execution_date=20250623T000000, start_date=20250624T015716, end_date=20250624T015716
[2025-06-24T01:57:16.277+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 26 for task extract ([Errno 2] No such file or directory: '/app/data/input.csv'; 2324)
[2025-06-24T01:57:16.319+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-24T01:57:16.344+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-24T01:57:16.347+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
